include:
  project: gcp-solutions/hcls/claims-modernization/gitlab-ci
  file: /.gitlab/ci/.deploy.gitlab-ci.yml

variables:
  # Path to the Namespace of the Application(s) Projects with micro-services.
  # Assumption: All of them are under the same hierarchy and same namespace.
  #In this example all Applications are in the same namespace as DeployApplications .
  APPLICATION_NAMESPACE: ${CI_PROJECT_NAMESPACE}

  #Sharing same Agent, but could use different agents
  GITLAB_AGENT: "gcp-solutions/hcls/claims-modernization/gitlab-test-examples/gitlab-gke:gitlab-agent-priorauth"
  KUBE_CONTEXT_DEMO: $GITLAB_AGENT
  KUBE_CONTEXT_TEST: $GITLAB_AGENT
  KUBE_CONTEXT_DEV: $GITLAB_AGENT

stages:
- deploy
- destroy


















