include:
  project: gcp-solutions/hcls/claims-modernization/gitlab-ci
  file: /.gitlab/ci/.deploy.gitlab-ci.yml

variables:
  # Path to the Namespace of the Application(s) Projects with micro-services.
  # Assumption: All of them are under the same hierarchy and same namespace.
  #In this example all Applications are in the same namespace as DeployApplications .
  APPLICATION_NAMESPACE: ${CI_PROJECT_NAMESPACE}

  # Commenting Out any of the KUBE_CONTEXT line will disable deployment into that environment.
  #Sharing same Agent, but could use different agents
  KUBE_CONTEXT_DEMO: "gcp-solutions/hcls/claims-modernization/gitlab-test-examples/gitlab-gke:gitlab-agent-priorauth"
  KUBE_CONTEXT_TEST: "gcp-solutions/hcls/claims-modernization/gitlab-test-examples/gitlab-gke:gitlab-agent-priorauth"
  KUBE_CONTEXT_DEV: "gcp-solutions/hcls/claims-modernization/gitlab-test-examples/gitlab-gke:gitlab-agent-priorauth"

stages:
- deploy
- destroy


















