include:
  project: gcp-solutions/hcls/claims-modernization/gitlab-ci
  file: .gitlab/ci/deploy.gitlab-ci.yml

variables:
  CONTAINER_REGISTRY: "registry.gitlab.com"
  APP_PATH: ${CI_PROJECT_NAMESPACE} # Namespace of the Projects with Application Images. Assumption: All of them are under same hierarchy with ProjectName==ApplicationName. In this example all Applications are in the sane namespace as this file.
  APP_REPO: ${CONTAINER_REGISTRY}/${APP_PATH}

  # Commenting Out any of the KUBE_CONTEXT line will disable deployment into that environment.
  #Sharing same Agent, but could use different agents
  KUBE_CONTEXT_DEMO: "gcp-solutions/hcls/claims-modernization/gitlab-test-examples/gitlab-gke:gitlab-agent-priorauth"
  KUBE_CONTEXT_TEST: "gcp-solutions/hcls/claims-modernization/gitlab-test-examples/gitlab-gke:gitlab-agent-priorauth"
  KUBE_CONTEXT_DEV: "gcp-solutions/hcls/claims-modernization/gitlab-test-examples/gitlab-gke:gitlab-agent-priorauth"

stages:
- deploy
- destroy


















