#include:
#  project: gcp-solutions/hcls/claims-modernization/gitlab-ci
#  file: /.gitlab/ci/.deploy.gitlab-ci.yml

variables:
  # Path to the Namespace of the Application(s) Projects with micro-services.
  # Assumption: All of them are under the same hierarchy and same namespace.
  #In this example all Applications are in the same namespace as DeployApplications .
  APPLICATION_NAMESPACE: ${CI_PROJECT_NAMESPACE}

  #Sharing same Agent, but could use different agents
  GITLAB_AGENT: "gcp-solutions/hcls/claims-modernization/gitlab-test-examples/gitlab-gke:gitlab-agent-priorauth"
  KUBE_CONTEXT_DEMO: $GITLAB_AGENT
  KUBE_CONTEXT_TEST: $GITLAB_AGENT
  KUBE_CONTEXT_DEV: "gcp-solutions/hcls/claims-modernization/gitlab-test-examples/gitlab-gke:gitlab-agent-evekhm"

stages:
- deploy
- destroy
- test

test:
  image: google/cloud-sdk
  #before_script: *gcloud
  before_script:
  - apt-get update && apt-get install git
  stage: test
  script:
  - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
  - cat $HOME/.docker/config.json
  - git clone https://oauth2:$CDS_LIBRARY_TOKEN@gitlab.com/gcp-solutions/hcls/claims-modernization/pa-ref-impl/CDS-Library.git ${CI_PROJECT_DIR}/../CDS-Library


















