apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: applicationa
  name: applicationa
spec:
  replicas: 1
  selector:
    matchLabels:
      application: applicationa
  template:
    metadata:
      labels:
        application: applicationa
    spec:
      containers:
      - image: __IMAGE_TAG__
        name: applicationa
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always