apiVersion: v1
kind: Service
metadata:
  labels:
    app: applicationa
  name: a-service
spec:
  type: LoadBalancer
  ports:
    - name: "5001"
      port: 5001
      protocol: TCP
      targetPort: 80
  selector:
    app: applicationa
