apiVersion: v1
kind: Service
metadata:
  labels:
    application: applicationa
  name: applicationa
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 80
  selector:
    application: applicationa
  sessionAffinity: None
  type: LoadBalancer