apiVersion: v1
kind: Service
metadata:
  labels:
    application: applicationb
  name: applicationb
spec:
  ports:
  - port: 5002
    protocol: TCP
    targetPort: 80
  selector:
    application: applicationb
  sessionAffinity: None
  type: LoadBalancer